### ISSUE TITLE
is your config.php file needed?

### ISSUE THREAD

**Issue by danmarsden** [markanyx/local_wswizard#12]
I was about to report...
please don't pollute the $CFG var with plugin specific settings like $CFG->pluginlocal - please use the config_plugins apis to set and use plugin specific settings..

But I'm not sure that your config.php file is actually used? - can it be deleted?

**Comment by danmarsden** [comment]
https://github.com/markanyx/local_wswizard/blob/master/config.php

**Comment by markanyx** [comment]
Right on. It's deleted. Thanks
