### ISSUE TITLE
Missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [markanyx/local_wswizard#6]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin doesn't appear to store any user data so you should be able to implement the simple null provider class.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

**Comment by danmarsden** [comment]
Ah.. missed you had user information in the tables. You won't be able to use null provider, you will need to  implement support for those tables

**Comment by markanyx** [comment]
Will do. In our logs, we have the username right now stored in the table, however, if only the user ID is stored, will we still have to implement support for the table?

**Comment by danmarsden** [comment]
yeah - if username or id are stored you need it covered in the privacy api.

storing username is bad practice btw - it's half of the users credentials so should be treated as "private" and not stored if possible - (use the userid it's better for SQL anyway.)

also - privacy api implementation is not a blocker for plugins db approval unless your plugin interacts with an external API/service... your plugin doesn't do this so it's not a blocker for plugins db approval, but still nice to add in.

**Comment by markanyx** [comment]
Privacy API added and Log table cleaned up. Thank you
